# Site
repository: jonathanbalagot
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Jonathan Balagot
title: Corporate IT Engineer / Senior Systems Administrator
email: resume@jonathanbalagot.com
website: jonathanbalagot.com

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: facespics
#github_username:  sproogen
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
linkedin_username: jonathan-balagot
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
#- title: jonathanbalagot.com
#  icon: fas fa-globe
#  url: https://jonathanbalagot.com
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Jonathan and I'm a IT Engineer experienced in on premise and cloud infrastructure with 8+ years of technical experience. 
  Extensive experience deploying, updating, migrating and maintaining Active Directory, Azure Active Directory, AWS, Azure, and GCP environments. 
  Heavy experience with SCCM (remote control, third party application deployment, patch management, monitoring, OS deployment). 
  Experienced with MDM tools in corporate environments (BYOD, Zero Touch, application deployment, profile management, Intune/Endpoint 
  and Apple Business Manager). 

content:
  - title: Technical Experience
    layout: text
    content: | # this will include new lines to allow paragraphs
      - Active Directory, Azure Active Directory, Google Workspace, OKTA, M365
      - Exchange 2013/2016, Google Mail
      - Patch Management and Vendor Updates
      - Vulnerability Assessment / Remediation
      - Server and Storage Infrastructure
      - 24x7 End User and Server Support
      - Authentication Protocols (MFA/SAML/ADFS/OICD/OAuth/SCIM)
      - Agile Methodology
      - Cloud: Azure, AWS, GCP
      - Virtualization: VMWare, Hyper V, ESXi
      - Deployment: SCCM, Symantec
      - Scripting: Powershell, Bash
      - MDM: Apple Business Manager, Workspace ONE UEM, Intune/Endpoint
      - Monitoring: DataDog, Sumologic, AWS CloudTrail, Cloud Audit, Azure Log Analytics, Log Rhythm, SCOM
      - Networking: VLAN, DNS, DHCP, TCP/IP



  - title: Professional Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Symbiont
        link: symbiont.io
        # link_text: boringcompany.com
        sub_title: Corporate IT Engineer
        caption: January 2022 – Present
        quote: >
          Symbiont is a leading technology company focused on solving complex global finance problems using a novel enterprise blockchain solution.
        description: | # this will include new lines to allow paragraphs
            - Maintained company cloud infrastructure (GCP, AWS, Azure) by managing virtual machines (AWS ECS, Azure VM, and Google Compute), 
            managing storage (AWS S3 and Google Buckets) and IAM to create/maintain RBAC group policies
            - Managed company collaboration environment, Google Workspace by creating accounts, mailboxes, setting Google Drive sharing permissions 
            and facilitating calendar meetings.
            - Set up the S/MIME email for encryption and tiered life cycle rules Amazon S3/Cloudfront for secure file transfer between company 
            and clients. Managed use access with Cognito.
            - Acted as a SME for company IDP using SAML and SCIM. OKTA was used as primary and Google Workspace/M365/Auth0 as secondary
            - SME for company SaaS applications, such as Notion, Github, JIRA, Greenhouse, Lattice, O’Reilly, Expensify, KnowBe4, Lucidchart, 
            Miro, Organimi, Zoom, WebEx
            - Reduced company financial burden by managing scalable resources for storage and virtualization along with taking ownership of 
            technical support system to eliminate the need for outsourced helpdesk. Tasked with remediating IT related hardware, access and 
            licensing issues
            - Managed DNS hostnames through Cloudflare and Route53 to ensure proper propagation of company website and auxiliary domains
            - Maintained company Slack channels by setting permissions for guest and application access
            - Maintained user access for employees from policy management, onboarding/off-boarding to decommissioning user equipment as necessary
            - Redesigned laptop deployment to use Apple Zero-Touch and MDM for MacBooks with Apple Business Manager and VMWare Workspace ONE.
            - Reviewed access logs through Datadog and Sumologic as SIEM tools and resolved security issues 
            - Facilitated the deployment of 1Password for centralized storage of secured passwords, secrets, and keys
            - Integrated several security tools such as Drata into cloud resources for audit compliance and risk compliance following SOC2 
            and Laceworks for GCP and AWS for security posture
            
      - layout: left
        title: Symbiont
        link: symbiont.io
        # link_text: boringcompany.com
        sub_title: Corporate IT Engineer
        caption: January 2022 – Present
        quote: >
          Symbiont is a leading technology company focused on solving complex global finance problems using a novel enterprise blockchain solution.
        description: | # this will include new lines to allow paragraphs
            - Maintained company cloud infrastructure (GCP, AWS, Azure) by managing virtual machines (AWS ECS, Azure VM, and Google Compute), 
            managing storage (AWS S3 and Google Buckets) and IAM to create/maintain RBAC group policies
            - Managed company collaboration environment, Google Workspace by creating accounts, mailboxes, setting Google Drive sharing permissions 
            and facilitating calendar meetings.
            - Set up the S/MIME email for encryption and tiered life cycle rules Amazon S3/Cloudfront for secure file transfer between company 
            and clients. Managed use access with Cognito.
            - Acted as a SME for company IDP using SAML and SCIM. OKTA was used as primary and Google Workspace/M365/Auth0 as secondary
            - SME for company SaaS applications, such as Notion, Github, JIRA, Greenhouse, Lattice, O’Reilly, Expensify, KnowBe4, Lucidchart, 
            Miro, Organimi, Zoom, WebEx
            - Reduced company financial burden by managing scalable resources for storage and virtualization along with taking ownership of 
            technical support system to eliminate the need for outsourced helpdesk. Tasked with remediating IT related hardware, access and 
            licensing issues
            - Managed DNS hostnames through Cloudflare and Route53 to ensure proper propagation of company website and auxiliary domains
            - Maintained company Slack channels by setting permissions for guest and application access
            - Maintained user access for employees from policy management, onboarding/off-boarding to decommissioning user equipment as necessary
            - Redesigned laptop deployment to use Apple Zero-Touch and MDM for MacBooks with Apple Business Manager and VMWare Workspace ONE.
            - Reviewed access logs through Datadog and Sumologic as SIEM tools and resolved security issues 
            - Facilitated the deployment of 1Password for centralized storage of secured passwords, secrets, and keys
            - Integrated several security tools such as Drata into cloud resources for audit compliance and risk compliance following SOC2 
            and Laceworks for GCP and AWS for security posture


  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Monroe College, New York
        sub_title: •	Associates in Science: Computer Information Systems
        description: | # this will include new lines to allow paragraphs
          - Summa Cum Laude.
          - President’s List
          - Dean’s List


  #- title: A Little More About Me
   # layout: text
    #content: | # this will include new lines to allow paragraphs
     # Alongside my interests in networks and software engineering some of my other interests and hobbies are:



# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
